In [0]:
import numpy as np
from sklearn.model_selection import train_test_split

In [0]:
X, Y = np.arange(20).reshape((10, 2)), range(10)

In [0]:
X

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [0]:
Y

range(0, 10)

In [0]:
X_train1,X_test1,Y_train1,Y_test1 = train_test_split(X, Y)

In [0]:
X_train1

array([[ 6,  7],
       [ 8,  9],
       [14, 15],
       [16, 17],
       [12, 13],
       [ 4,  5],
       [ 2,  3]])

In [0]:
Y_train1

[3, 4, 7, 8, 6, 2, 1]

In [0]:
X_train2, X_test2, Y_train2, Y_test2 = train_test_split(X, Y)

In [0]:
X_train2

array([[ 6,  7],
       [ 8,  9],
       [ 2,  3],
       [ 4,  5],
       [12, 13],
       [16, 17],
       [18, 19]])

In [0]:
X_train3, X_test3,Y_train3,Y_test3 = train_test_split(X, Y, random_state = 8)

In [0]:
X_train3

array([[ 0,  1],
       [ 4,  5],
       [10, 11],
       [14, 15],
       [ 2,  3],
       [ 8,  9],
       [ 6,  7]])

In [0]:
X_train4, X_test4, Y_train4, Y_test4 = train_test_split(X, Y, random_state = 8)

In [0]:
X_train4

array([[ 0,  1],
       [ 4,  5],
       [10, 11],
       [14, 15],
       [ 2,  3],
       [ 8,  9],
       [ 6,  7]])